#!/bin/bash
# generate-rbac-resources.sh
#
# Generates a custom-resources.yaml file with your namespace and group names.
# Run this script, fill in your values (or use defaults), and it creates the file.
#
# Usage: ./generate-rbac-resources.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/custom-resources.yaml"

# ============ DEFAULTS - EDIT THESE OR ENTER AT RUNTIME ============
DEFAULT_NS_DEV="development"
DEFAULT_NS_STAGING="staging"
DEFAULT_NS_PROD="production"

DEFAULT_GROUP_ADMIN="platform-admins"
DEFAULT_GROUP_DEV="developers"
DEFAULT_GROUP_DEVOPS="devops"
# ====================================================================

echo ""
echo "=== RBAC Configuration ==="
echo ""

# Namespaces
read -p "Dev namespace [${DEFAULT_NS_DEV}]: " NS_DEV
NS_DEV="${NS_DEV:-$DEFAULT_NS_DEV}"

read -p "Staging namespace [${DEFAULT_NS_STAGING}]: " NS_STAGING
NS_STAGING="${NS_STAGING:-$DEFAULT_NS_STAGING}"

read -p "Production namespace [${DEFAULT_NS_PROD}]: " NS_PROD
NS_PROD="${NS_PROD:-$DEFAULT_NS_PROD}"

echo ""

# Groups
read -p "Admin group [${DEFAULT_GROUP_ADMIN}]: " GROUP_ADMIN
GROUP_ADMIN="${GROUP_ADMIN:-$DEFAULT_GROUP_ADMIN}"

read -p "Developer group [${DEFAULT_GROUP_DEV}]: " GROUP_DEV
GROUP_DEV="${GROUP_DEV:-$DEFAULT_GROUP_DEV}"

read -p "DevOps group [${DEFAULT_GROUP_DEVOPS}]: " GROUP_DEVOPS
GROUP_DEVOPS="${GROUP_DEVOPS:-$DEFAULT_GROUP_DEVOPS}"

echo ""
echo "Generating ${OUTPUT_FILE}..."

cat > "$OUTPUT_FILE" << EOF
# custom-resources.yaml
# Generated by generate-rbac-resources.sh
#
# Groups:
#   - ${GROUP_ADMIN} - Full cluster access
#   - ${GROUP_DEV} - Full access to ${NS_DEV} namespace
#   - ${GROUP_DEVOPS} - Deploy access to ${NS_STAGING} and ${NS_PROD}
#
# Apply with: kubectl apply -f custom-resources.yaml

# ============ NAMESPACES ============
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${NS_DEV}
  labels:
    environment: ${NS_DEV}
    team: ${GROUP_DEV}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${NS_STAGING}
  labels:
    environment: ${NS_STAGING}
    team: ${GROUP_DEVOPS}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${NS_PROD}
  labels:
    environment: ${NS_PROD}
    team: ${GROUP_DEVOPS}

# ============ CLUSTER ROLES ============
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes", "namespaces"]
    verbs: ["get", "list", "watch"]

# ============ ROLES ============
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${NS_DEV}
  name: developer-full-access
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["pods", "deployments", "deployments/scale", "replicasets", "statefulsets", "daemonsets", "jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["", "networking.k8s.io"]
    resources: ["services", "endpoints", "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/exec", "pods/portforward"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${NS_STAGING}
  name: devops-deploy-access
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${NS_PROD}
  name: devops-deploy-access
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

# ============ CLUSTER ROLE BINDINGS ============
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${GROUP_ADMIN}-full-access
subjects:
  - kind: Group
    name: ${GROUP_ADMIN}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: platform-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-teams-cluster-viewer
subjects:
  - kind: Group
    name: ${GROUP_DEV}
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: ${GROUP_DEVOPS}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-viewer
  apiGroup: rbac.authorization.k8s.io

# ============ ROLE BINDINGS ============
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${GROUP_DEV}-${NS_DEV}-access
  namespace: ${NS_DEV}
subjects:
  - kind: Group
    name: ${GROUP_DEV}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-full-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${GROUP_DEVOPS}-${NS_STAGING}-access
  namespace: ${NS_STAGING}
subjects:
  - kind: Group
    name: ${GROUP_DEVOPS}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devops-deploy-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${GROUP_DEVOPS}-${NS_PROD}-access
  namespace: ${NS_PROD}
subjects:
  - kind: Group
    name: ${GROUP_DEVOPS}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devops-deploy-access
  apiGroup: rbac.authorization.k8s.io
EOF

echo ""
echo "Done! Created: ${OUTPUT_FILE}"
echo ""
echo "Apply with:"
echo "  kubectl apply -f ${OUTPUT_FILE}"
echo ""
echo "Verify your permissions (as logged-in user):"
echo "  kubectl auth can-i --list -n ${NS_DEV}"
echo "  kubectl auth can-i --list -n ${NS_STAGING}"
echo "  kubectl auth can-i --list -n ${NS_PROD}"
echo ""
echo "Test specific actions (expected results depend on your group):"
echo "  kubectl auth can-i create deployments -n ${NS_DEV}    # ${GROUP_DEV}: yes, ${GROUP_DEVOPS}: no"
echo "  kubectl auth can-i update deployments -n ${NS_STAGING}  # ${GROUP_DEV}: no, ${GROUP_DEVOPS}: yes"
echo "  kubectl auth can-i delete pods -n ${NS_PROD}           # everyone: no"
